CREATE TABLE Appointment (
  id VARCHAR(30) PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  userId VARCHAR(30) NOT NULL,
  testId VARCHAR(30) NOT NULL,
  date DATE NOT NULL,
  timeSlot VARCHAR(64) NOT NULL,
  status ENUM('PENDING','CONFIRMED','RESCHEDULED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'CONFIRMED',
  patientName VARCHAR(255) NOT NULL,
  patientAge INT NULL,
  notes TEXT NULL,
  collectionType ENUM('LAB','HOME') NOT NULL DEFAULT 'HOME',
  addressId VARCHAR(30) NULL,
  familyMemberId VARCHAR(30) NULL,
  location VARCHAR(255) NOT NULL DEFAULT 'Home collection',
  deliveryAddress TEXT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  originalPrice DECIMAL(10,2) NULL,
  membershipDiscount DECIMAL(10,2) NULL,
  cardDiscount DECIMAL(10,2) NULL,
  referralDiscount DECIMAL(10,2) NULL,
  walletDiscount DECIMAL(10,2) NULL,
  finalPrice DECIMAL(10,2) NULL,
  payableAmount DECIMAL(10,2) NULL,
  paymentStatus ENUM('PENDING','PAID','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',
  paymentMethod ENUM('UPI','CARD','COD','WALLET') NULL,
  reminderEnabled TINYINT(1) NOT NULL DEFAULT 1,
  reminderSentAt DATETIME(3) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deletedAt DATETIME(3) NULL,
  INDEX (userId, status),
  INDEX (date),
  CONSTRAINT fk_appt_user FOREIGN KEY (userId) REFERENCES User(id),
  CONSTRAINT fk_appt_test FOREIGN KEY (testId) REFERENCES Test(id),
  CONSTRAINT fk_appt_addr FOREIGN KEY (addressId) REFERENCES Address(id),
  CONSTRAINT fk_appt_fam FOREIGN KEY (familyMemberId) REFERENCES FamilyMember(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
