CREATE TABLE AuditLog (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NULL,
  action VARCHAR(128) NOT NULL,
  entity VARCHAR(128) NOT NULL,
  entityId VARCHAR(64) NULL,
  meta JSON NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX (entity, entityId),
  CONSTRAINT fk_audit_user FOREIGN KEY (userId) REFERENCES User(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
