CREATE TABLE FamilyMember (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NOT NULL,
  name VARCHAR(255) NOT NULL,
  relation ENUM('SPOUSE','PARENT','CHILD','SIBLING','OTHER') NOT NULL,
  dateOfBirth DATETIME NULL,
  gender ENUM('MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY') NULL,
  age INT NULL,
  mobile VARCHAR(32) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX (userId),
  CONSTRAINT fk_family_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
