CREATE TABLE MembershipPlan (
  id VARCHAR(30) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  price DECIMAL(10,2) NOT NULL,
  durationDays INT NOT NULL,
  description TEXT NOT NULL,
  isFree TINYINT(1) NOT NULL DEFAULT 0,
  flatDiscountPercent DECIMAL(5,2) NOT NULL DEFAULT 0,
  maxFamilyMembers INT NOT NULL DEFAULT 4,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
