CREATE TABLE Membership (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NOT NULL,
  planId VARCHAR(30) NOT NULL,
  number VARCHAR(64) NOT NULL UNIQUE,
  startsAt DATETIME(3) NOT NULL,
  expiresAt DATETIME(3) NOT NULL,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX (userId, isActive),
  CONSTRAINT fk_mem_user FOREIGN KEY (userId) REFERENCES User(id),
  CONSTRAINT fk_mem_plan FOREIGN KEY (planId) REFERENCES MembershipPlan(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
