CREATE TABLE Notification (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NOT NULL,
  type ENUM(
    'APPOINTMENT_CONFIRMATION',
    'APPOINTMENT_REMINDER',
    'APPOINTMENT_CANCELLATION',
    'APPOINTMENT_RESCHEDULED',
    'REPORT_AVAILABLE',
    'MEMBERSHIP_EXPIRY',
    'PROMOTIONAL'
  ) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  isRead TINYINT(1) NOT NULL DEFAULT 0,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX (userId, isRead),
  CONSTRAINT fk_notif_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
