CREATE TABLE PlatformSettings (
  id VARCHAR(30) PRIMARY KEY DEFAULT 'default',
  paymentPromoPercent DECIMAL(5,2) NOT NULL DEFAULT 30,
  paymentPromoActive TINYINT(1) NOT NULL DEFAULT 1,
  paymentPromoApplyToAllUsers TINYINT(1) NOT NULL DEFAULT 1,
  promoLabel VARCHAR(255) NOT NULL DEFAULT 'Extra off special price at payment',
  updatedByUserId VARCHAR(30) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
