CREATE TABLE Referral (
  id VARCHAR(30) PRIMARY KEY,
  referrerId VARCHAR(30) NOT NULL,
  referredUserId VARCHAR(30) NOT NULL UNIQUE,
  bonusAmount DECIMAL(10,2) NOT NULL,
  creditedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX (referrerId),
  CONSTRAINT fk_ref_referrer FOREIGN KEY (referrerId) REFERENCES User(id) ON DELETE CASCADE,
  CONSTRAINT fk_ref_referred FOREIGN KEY (referredUserId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
