CREATE TABLE RefreshToken (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NOT NULL,
  tokenHash VARCHAR(255) NOT NULL,
  userAgent VARCHAR(512) NULL,
  expiresAt DATETIME(3) NOT NULL,
  revokedAt DATETIME(3) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX (userId),
  INDEX (tokenHash),
  CONSTRAINT fk_refresh_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
