CREATE TABLE TestParameter (
  id VARCHAR(30) PRIMARY KEY,
  testId VARCHAR(30) NOT NULL,
  name VARCHAR(255) NOT NULL,
  unit VARCHAR(64) NULL,
  INDEX (testId),
  CONSTRAINT fk_param_test FOREIGN KEY (testId) REFERENCES Test(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
