CREATE TABLE TestReport (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NOT NULL,
  appointmentId VARCHAR(30) NOT NULL,
  status ENUM('PENDING','PROCESSING','AVAILABLE') NOT NULL DEFAULT 'PENDING',
  fileUrl TEXT NULL,
  fileName VARCHAR(255) NULL,
  fileMimeType VARCHAR(128) NULL,
  fileSize INT NULL,
  summary TEXT NULL,
  releasedAt DATETIME(3) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX (userId),
  CONSTRAINT fk_report_user FOREIGN KEY (userId) REFERENCES User(id),
  CONSTRAINT fk_report_appt FOREIGN KEY (appointmentId) REFERENCES Appointment(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
