CREATE TABLE User (
  id VARCHAR(30) PRIMARY KEY,
  fullName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  mobile VARCHAR(32) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  dateOfBirth DATETIME NULL,
  gender ENUM('MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY') NULL,
  role ENUM('USER','ADMIN','SUPER_ADMIN') NOT NULL DEFAULT 'USER',
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  avatarUrl TEXT NULL,
  referralCode VARCHAR(64) NULL UNIQUE,
  referredByUserId VARCHAR(30) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deletedAt DATETIME(3) NULL,
  INDEX (referredByUserId),
  CONSTRAINT fk_user_referrer FOREIGN KEY (referredByUserId) REFERENCES User(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
