CREATE TABLE UserProfile (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NOT NULL UNIQUE,
  language VARCHAR(16) NOT NULL DEFAULT 'en',
  theme VARCHAR(32) NOT NULL DEFAULT 'system',
  notificationsOn TINYINT(1) NOT NULL DEFAULT 1,
  whatsappOn TINYINT(1) NOT NULL DEFAULT 1,
  locationLat DECIMAL(10,7) NULL,
  locationLng DECIMAL(10,7) NULL,
  CONSTRAINT fk_profile_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
