CREATE TABLE Wallet (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NOT NULL UNIQUE,
  balance DECIMAL(10,2) NOT NULL DEFAULT 0,
  referralBalance DECIMAL(10,2) NOT NULL DEFAULT 0,
  joiningBonusCredited TINYINT(1) NOT NULL DEFAULT 0,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX (userId),
  CONSTRAINT fk_wallet_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
