CREATE TABLE WhatsAppMessage (
  id VARCHAR(30) PRIMARY KEY,
  userId VARCHAR(30) NOT NULL,
  mobile VARCHAR(32) NOT NULL,
  template VARCHAR(128) NOT NULL,
  body TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'SENT',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX (userId),
  CONSTRAINT fk_wa_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
