/** Official HealthID Card diagnostic packages from the partner brochure (29 packages). */
export type HealthPackageDef = {
  name: string;
  shortDescription: string;
  description: string;
  preparation: string;
  includedTests: string[];
  mrp: number;
  specialPrice: number;
  isPopular?: boolean;
  reportHours?: number;
  sampleType?: string;
};

export const HEALTH_PACKAGES: HealthPackageDef[] = [
  {
    name: 'DIABETIC PANEL',
    shortDescription: 'Diabetic Panel — 14 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Diabetic Panel — 14 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Complete Blood Count (CBC)',
      'Glycated Haemoglobin (HbA1c)',
      'Lipid Profile',
      'LIVER FUNCTION TESTS',
      'Kidney Profile',
      'IRON PROFILE',
      'GFR (GLOMERULAR FILTRATION RATE)',
      'THYROID PROFILE -3 (T3 T4 TSH)',
      'Microalbumin & Creatinine ratio (Urine)',
      'Amylase (Serum)',
      'Lipase',
      'Insulin Fasting',
      'C-Peptide',
      'Ketone (Acetone, Hydroxybutyrate), serum',
    ],
    mrp: 3800,
    specialPrice: 1999,
    isPopular: true,
  },
  {
    name: 'DIABETIC ADVANCE',
    shortDescription: 'Diabetic Advance — 6 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Diabetic Advance — 6 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Insulin Fasting',
      'C-PEPTIDE (F)',
      'HOMA-IR',
      'Beta cell function',
      'Insulin sensitivity',
      'Glucose F (Blood Sugar Fasting)',
    ],
    mrp: 11000,
    specialPrice: 3999,
  },
  {
    name: 'INFERTILITY PROFILE - MALE',
    shortDescription: 'Infertility Profile - Male — 5 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Infertility Profile - Male — 5 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Thyroid Stimulating Hormone (TSH)',
      'LH, FSH, PRL',
      'Testosterone - Total',
      'Sex Hormone Binding Globulin (SHBG)',
      'ANTI SPERM ANTIBODY, SERUM',
    ],
    mrp: 3200,
    specialPrice: 2499,
  },
  {
    name: 'INFERTILITY PROFILE - FEMALE',
    shortDescription: 'Infertility Profile - Female — 6 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Infertility Profile - Female — 6 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Thyroid Stimulating Hormone (TSH)',
      'LH, FSH, PRL',
      'Testosterone - Total',
      'ESTRADIOL (E2)',
      'Anti Mullerian Hormone (AMH)',
      'Progesterone',
    ],
    mrp: 2800,
    specialPrice: 2399,
  },
  {
    name: 'PREGNANCY ANC PROFILE',
    shortDescription: 'Pregnancy Anc Profile — 8 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Pregnancy Anc Profile — 8 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Complete Blood Count (CBC) + ESR',
      'Glucose Random (Blood Sugar Random)',
      'ABO Group & RH Type (Blood Group)',
      'HIV 1 & 2 Antibody - Rapid',
      'Hepatitis B surface antigen (HBs Ag) (Rapid)',
      'THYROID PROFILE -3 (T3 T4 TSH)',
      'VDRL (Rapid)',
      'Hepatitis C virus (HCV Rapid)',
    ],
    mrp: 2200,
    specialPrice: 1499,
  },
  {
    name: 'APLA PROFILE',
    shortDescription: 'Apla Profile — 3 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Apla Profile — 3 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'ANTI PHOSPHOLIPID ANTIBODY (APL) - IgG, IgM',
      'Cardiolipin Antibodies IgA, IgG, IgM',
      'Lupus Anticoagulant (DRVVT)',
    ],
    mrp: 4800,
    specialPrice: 2699,
  },
  {
    name: 'BONE PROFILE',
    shortDescription: 'Bone Profile — 11 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Bone Profile — 11 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      '25 OH VITAMIN D 3 TOTAL',
      'Intact Parathyroid Hormone (iPTH)',
      'Calcium',
      'Phosphorous, serum',
      'Alkaline Phosphatase (ALP)',
      'Zinc SERUM',
      'Vitamin B12',
      'Magnesium',
      'Rheumatoid Factor (RA test) Quantitative',
      'Uric Acid',
      'Copper (Serum)',
    ],
    mrp: 4000,
    specialPrice: 2499,
  },
  {
    name: 'ARTHRITIS PROFILE',
    shortDescription: 'Arthritis Profile — 13 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Arthritis Profile — 13 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'LIVER FUNCTION TESTS',
      'Kidney Profile',
      'Lipid Profile',
      'C Reactive Protein (CRP) Quantitative',
      'Rheumatoid Factor (RA test) Quantitative',
      'Anti streptolysin-O (ASO) Titre',
      'Anti Cyclic Citrullinated Peptide Antibody (Anti-CCP)',
      'ANTI NUCLEAR ANTIBODY (ANA)',
      'IRON PROFILE',
      'Complete Blood Count (CBC) + ESR',
      'THYROID PROFILE -3 (T3 T4 TSH)',
      'GFR (GLOMERULAR FILTRATION RATE)',
      'HLA-B27 ESTIMATION',
    ],
    mrp: 6000,
    specialPrice: 3199,
  },
  {
    name: 'CANCER PANEL (MALE)',
    shortDescription: 'Cancer Panel (Male) — 6 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Cancer Panel (Male) — 6 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Alpha Fetoprotein (AFP), SERUM',
      'Beta Human Chorionic Gonadotropin Hormone (BHCG)',
      'Carcino embryonic antigen (CEA)',
      'PSA - Free (Prostate Specific Antigen Free)',
      'PSA - Total (Prostate Specific Antigen Total)',
      'CA19.9 - Pancreatic Cancer Marker',
    ],
    mrp: 5000,
    specialPrice: 2299,
  },
  {
    name: 'CANCER MARKER - 2 (FEMALE)',
    shortDescription: 'Cancer Marker - 2 (Female) — 7 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Cancer Marker - 2 (Female) — 7 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Complete Blood Count (CBC)',
      'Alpha Fetoprotein (AFP), SERUM',
      'Beta Human Chorionic Gonadotropin Hormone (BHCG)',
      'CA125 - Cancer Marker',
      'CA15.3 - Breast Cancer Marker',
      'CA19.9 - Pancreatic Cancer Marker',
      'Carcino embryonic antigen (CEA)',
    ],
    mrp: 5500,
    specialPrice: 2399,
  },
  {
    name: 'CARDIAC CARE PROFILE',
    shortDescription: 'Cardiac Care Profile — 11 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Cardiac Care Profile — 11 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Glucose R (Blood Sugar Random)',
      'Complete Blood Count (CBC)',
      'CPK-MB (Creatine Kinase Myocardial Band)',
      'Creatinine',
      'Electrolyte Panel - (Na, K, Cl)',
      'Homocysteine, Serum',
      'LACTATE DEHYDROGENASE (LDH)',
      'NT-Pro BNP',
      'SGOT; Aspartate Aminotransferase (AST)',
      'SGPT',
      'HS-CRP',
    ],
    mrp: 5200,
    specialPrice: 2799,
    isPopular: true,
  },
  {
    name: 'COMPLETE VITAMIN PROFILE',
    shortDescription: 'Complete Vitamin Profile — 12 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Complete Vitamin Profile — 12 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Vitamin D PROFILE (D2, D3, TOTAL D)',
      'VITAMIN A',
      'Vitamin B12',
      'Thiamine (VITAMIN B1)',
      'Riboflavin (VITAMIN B2)',
      'Niacin (VITAMIN B3)',
      'Pantothenic acid (VITAMIN B5)',
      'Pyridoxal 5 phosphate (VITAMIN B6)',
      'BIOTIN (VITAMIN B7)',
      'Folic Acid',
      'VITAMIN E',
      'VITAMIN K',
    ],
    mrp: 9500,
    specialPrice: 4999,
  },
  {
    name: 'COAGULATION PROFILE',
    shortDescription: 'Coagulation Profile — 6 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Coagulation Profile — 6 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Activated Partial Thromboplastin Time (APTT/PTTK)',
      'BLEEDING TIME AND CLOTTING TIME (BT, CT)',
      'Complete Blood Count (CBC)',
      'D-DIMER QUANTITATIVE',
      'FIBRINOGEN',
      'Prothrombin Time (PT) with INR',
    ],
    mrp: 4200,
    specialPrice: 2199,
  },
  {
    name: 'HAIRFALL PROFILE',
    shortDescription: 'Hairfall Profile — 15 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Hairfall Profile — 15 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Complete Blood Count (CBC)',
      '25 OH VITAMIN D 3 TOTAL',
      'Vitamin B12',
      'THYROID PROFILE -3 (T3 T4 TSH)',
      'IRON PROFILE',
      'FERRITIN',
      '5-Dihydrotestosterone (DHT)',
      'Sex Hormone Binding Globulin (SHBG)',
      'ANTI NUCLEAR ANTIBODY (ANA)',
      'C Reactive Protein (CRP) Quantitative',
      'CORTISOL, Serum',
      'Calcium',
      'Phosphorous, serum',
      'Magnesium',
      'Zinc SERUM',
    ],
    mrp: 8000,
    specialPrice: 3499,
  },
  {
    name: 'HEPATITIS PROFILE',
    shortDescription: 'Hepatitis Profile — 10 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Hepatitis Profile — 10 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'HEPATITIS B ENVELOPE ANTIGEN (HBeAg)',
      'Hepatitis B core antigen - Total',
      'Hepatitis A virus IgM Antibodies',
      'Hepatitis A virus IgG Antibodies (HAV IgG)',
      'Hepatitis A virus Total Antibodies (HAV-Total)',
      'Hepatitis B core antibody IgM (HBc IgM)',
      'Hepatitis B Envelope antibody (Anti-HBeAb)',
      'Hepatitis B surface Antibody (HBsAb)',
      'Hepatitis B surface antigen (HBs Ag) CLIA',
      'Hepatitis C virus (HCV) CLIA',
    ],
    mrp: 7000,
    specialPrice: 3599,
  },
  {
    name: 'THALASSEMIA PROFILE',
    shortDescription: 'Thalassemia Profile — 6 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Thalassemia Profile — 6 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Complete Blood Count (CBC) + ESR',
      'Peripheral Blood Smear (PBS OR PBF)',
      'Hb Electrophoresis by HPLC',
      'IRON',
      'TIBC (Total Iron Binding Capacity)',
      'FERRITIN',
    ],
    mrp: 3200,
    specialPrice: 1399,
  },
  {
    name: 'PCOD EXTENDED PROFILE',
    shortDescription: 'Pcod Extended Profile — 13 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Pcod Extended Profile — 13 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Glucose F (Blood Sugar Fasting)',
      'Insulin Fasting',
      'Beta cell function',
      'Insulin sensitivity',
      'HOMA-IR',
      'Lipid Profile',
      'FSH (Follicle Stimulating Hormone)',
      'Luteinising Hormone (LH)',
      'Prolactin (PRL)',
      'Testosterone - Total',
      'Dehydroepiandrosterone Sulphate (DHEA-S)',
      'TSH Ultrasensitive',
      'Anti Mullerian Hormone (AMH)',
    ],
    mrp: 8500,
    specialPrice: 4299,
  },
  {
    name: 'PCOD MINI',
    shortDescription: 'Pcod Mini — 10 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Pcod Mini — 10 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Luteinising Hormone (LH)',
      'Follicle Stimulating Hormone (FSH)',
      'Prolactin',
      'Thyroid Stimulating Hormone (TSH)',
      'Testosterone - Total',
      'Insulin - Fasting',
      'Dehydroepiandrosterone Sulphate (DHEAS)',
      'Glycosylated Hemoglobin (GHb/HBA1c)',
      'Complete Blood Count (CBC), Haemogram - 3PART',
      'Estradiol (E2) Estrogen',
    ],
    mrp: 3500,
    specialPrice: 1999,
    isPopular: true,
  },
  {
    name: 'PRE SURGERY PROFILE',
    shortDescription: 'Pre Surgery Profile — 6 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Pre Surgery Profile — 6 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'BLEEDING TIME AND CLOTTING TIME (BT, CT)',
      'Urea (Blood)',
      'Creatinine',
      'Triple H Rapid - (HIV, HBsAg, HCV)',
      'Complete Blood Count (CBC)',
      'Glucose R (Blood Sugar Random)',
    ],
    mrp: 1800,
    specialPrice: 1099,
  },
  {
    name: 'FULL BODY CHECK-UP ADVANCE',
    shortDescription: 'Full Body Check-Up Advance — 12 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Full Body Check-Up Advance — 12 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Complete Blood Count (CBC), Haemogram - 5PART',
      'Liver Profile (10 Tests)',
      'Lipid (Cholesterol) Profile (8 Tests)',
      'Glycosylated Hemoglobin (GHb/HBA1c)',
      '25-Hydroxy Vitamin D',
      'Vitamin - B12',
      'Glucose - Fasting',
      'Urine Routine Manual',
      'Thyroid Profile 1 (3 Tests)',
      'Iron Profile',
      'Renal Profile Extended',
      'GFR (GLOMERULAR FILTRATION RATE)',
    ],
    mrp: 5200,
    specialPrice: 1299,
    isPopular: true,
  },
  {
    name: 'WOMEN CARE',
    shortDescription: 'Women Care — 13 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Women Care — 13 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Thyroid Profile 3 (5 Tests)',
      'Liver Profile (10 Tests)',
      'Renal Profile Mini (7 Tests)',
      'Lipid (Cholesterol) Profile (8 Tests)',
      'Estradiol (E2) Estrogen',
      'Complete Blood Count (CBC) Haemogram - 5PART',
      'Iron Serum',
      '25-Hydroxy Vitamin D',
      'Vitamin - B12',
      'Glycosylated Hemoglobin (GHb/HBA1c)',
      'Luteinising Hormone (LH)',
      'Follicle Stimulating Hormone (FSH)',
      'Prolactin',
    ],
    mrp: 4500,
    specialPrice: 1599,
    isPopular: true,
  },
  {
    name: 'FULL BODY BASIC',
    shortDescription: 'Full Body Basic — 8 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Full Body Basic — 8 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Glucose - Fasting',
      'Complete Blood Count (CBC) Haemogram - 3PART',
      'Erythrocyte Sedimentation Rate (ESR)',
      'Liver Profile (10 Tests)',
      'Thyroid Profile 1 (3 Tests)',
      'Renal Profile Extended',
      'Lipid (Cholesterol) Profile (8 Tests)',
      'HBA1C',
    ],
    mrp: 3500,
    specialPrice: 999,
    isPopular: true,
  },
  {
    name: 'FITNESS CARE',
    shortDescription: 'Fitness Care — 12 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Fitness Care — 12 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Complete Blood Count (CBC), Haemogram - 5PART',
      'GFR (GLOMERULAR FILTRATION RATE)',
      'Liver Profile (10 Tests)',
      'Lipid (Cholesterol) Profile (8 Tests)',
      'Iron Serum',
      'Glycosylated Hemoglobin (GHb/HBA1c)',
      '25-Hydroxy Vitamin D',
      'Vitamin - B12',
      'Testosterone - Total',
      'CRP Cardiac (hsCRP) Quantitative',
      'Thyroid Profile 1 (3 Tests)',
      'Renal Profile Extended',
    ],
    mrp: 4200,
    specialPrice: 1699,
  },
  {
    name: 'WELLNESS PLUS',
    shortDescription: 'Wellness Plus — 13 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Wellness Plus — 13 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Complete Blood Count (CBC), Haemogram - 5PART',
      'Glycosylated Hemoglobin (GHb/HBA1c)',
      'Lipid (Cholesterol) Profile (8 Tests)',
      'Liver Profile (10 Tests)',
      'GFR (GLOMERULAR FILTRATION RATE)',
      '25-Hydroxy Vitamin D',
      'Vitamin - B12',
      'Testosterone - Total',
      'Amylase Serum',
      'Lipase',
      'Thyroid Profile 1 (3 Tests)',
      'Renal Profile Extended',
      'Iron Profile',
    ],
    mrp: 4200,
    specialPrice: 1699,
  },
  {
    name: 'FITNESS SMART',
    shortDescription: 'Fitness Smart — 13 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Fitness Smart — 13 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Thyroid Profile 3 (5 Tests)',
      'Liver Profile (10 Tests)',
      'Renal Profile Mini (7 Tests)',
      'Iron Serum',
      'Complete Blood Count (CBC), Haemogram - 5PART',
      'Glycosylated Hemoglobin (GHb/HBA1c)',
      '25-Hydroxy Vitamin D',
      'Vitamin - B12',
      'Urine Routine Manual',
      'Rheumatoid Factor (RA test) Quantitative',
      'CRP Cardiac (hsCRP) Quantitative',
      'Lipid (Cholesterol) Profile (8 Tests)',
      'Homocysteine Serum',
    ],
    mrp: 5500,
    specialPrice: 2299,
  },
  {
    name: 'BAD OBSTETRIC HISTORY PROFILE',
    shortDescription: 'Bad Obstetric History Profile — 6 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Bad Obstetric History Profile — 6 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'ANTI NUCLEAR ANTIBODY (ANA)',
      'ANTI PHOSPHOLIPID ANTIBODY (APL) - IgG, IgM',
      'Lupus Anticoagulant (DRVVT)',
      'Thyroid Stimulating Hormone (TSH)',
      'TORCH-10',
      'Cardiolipin Antibodies IgA, IgG, IgM',
    ],
    mrp: 9500,
    specialPrice: 5199,
  },
  {
    name: 'ARTHRITIS PANEL (MINI)',
    shortDescription: 'Arthritis Panel (Mini) — 6 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Arthritis Panel (Mini) — 6 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'ANTI NUCLEAR ANTIBODY (ANA)',
      'Rheumatoid Factor (RA test) Quantitative',
      'C Reactive Protein (CRP) Quantitative',
      'Anti streptolysin-O (ASO) Titre',
      'Uric Acid',
      'Urine R/M (Urine Analysis)',
    ],
    mrp: 3500,
    specialPrice: 1699,
  },
  {
    name: 'ARTHRITIS PROFILE ADVANCE',
    shortDescription: 'Arthritis Profile Advance — 17 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Arthritis Profile Advance — 17 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'LIVER FUNCTION TESTS',
      'Lipid Profile',
      'Kidney Profile',
      'IRON PROFILE',
      'THYROID PROFILE -3 (T3 T4 TSH)',
      'Glycated Haemoglobin (HbA1c)',
      'C Reactive Protein (CRP) Quantitative',
      'Rheumatoid Factor (RA test) Quantitative',
      'Anti streptolysin-O (ASO) Titre',
      'ANTI NUCLEAR ANTIBODY (ANA)',
      'Anti Cyclic Citrullinated Peptide Antibody (Anti-CCP)',
      'HLA-B27 ESTIMATION',
      'Phosphorous, serum',
      '25 OH VITAMIN D 3 TOTAL',
      'Vitamin B12',
      'Complete Blood Count (CBC)',
      'Complement 4 (C4)',
    ],
    mrp: 6500,
    specialPrice: 3999,
  },
  {
    name: 'VITAMIN B COMPLEX PROFILE',
    shortDescription: 'Vitamin B Complex Profile — 8 parameters bundled at HealthID Card special rate with free home collection.',
    description: 'Vitamin B Complex Profile — 8 parameters bundled at HealthID Card special rate with free home collection. Processed at NABL partner labs with digital reports on WhatsApp.',
    preparation: 'Follow fasting instructions as advised for included parameters. Phlebotomist will confirm at collection.',
    includedTests: [
      'Thiamine (VITAMIN B1)',
      'Niacin (VITAMIN B3)',
      'Pyridoxal 5 phosphate (VITAMIN B6)',
      'Folic Acid',
      'Riboflavin (VITAMIN B2)',
      'Pantothenic acid (VITAMIN B5)',
      'BIOTIN (VITAMIN B7)',
      'Vitamin B12',
    ],
    mrp: 9500,
    specialPrice: 4499,
  },
];
