/** HealthID Wallet — fintech rules (product config). */
export const WALLET_RULES = {
  JOINING_BONUS: 250,
  REFERRAL_BONUS: 1000,
  REFERRAL_PER_TEST: 200,
}

export const WalletTxnType = {
  JOINING_BONUS: 'JOINING_BONUS',
  REFERRAL_EARNED: 'REFERRAL_EARNED',
  REFERRAL_REDEEMED: 'REFERRAL_REDEEMED',
  WALLET_REDEEMED: 'WALLET_REDEEMED',
  REFUND: 'REFUND',
  ADJUSTMENT: 'ADJUSTMENT',
}
